quarkus.package.jar.type=legacy-jar

# Cognito JWT validation
mp.jwt.verify.publickey.location=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gH2XpL8oM/.well-known/jwks.json
mp.jwt.verify.issuer=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gH2XpL8oM
mp.jwt.verify.audiences=7mie7eekl9csfobgtqggtflgbp

# CORS validation
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://dash.srmanda.com,http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type
quarkus.http.cors.exposed-headers=Authorization