quarkus.package.jar.type=legacy-jar

# Cognito JWT validation
mp.jwt.verify.publickey.location=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gH2XpL8oM/.well-known/jwks.json
mp.jwt.verify.issuer=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gH2XpL8oM
mp.jwt.verify.audiences=7mie7eekl9csfobgtqggtflgbp
quarkus.http.auth.permission.authenticated.paths=/jobs/*,/auth/*
quarkus.http.auth.permission.authenticated.policy=authenticated